//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GodAndMe.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_nl {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_nl() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GodAndMe.Resx.AppResources.nl", typeof(AppResources_nl).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string AddSavings {
            get {
                return ResourceManager.GetString("AddSavings", resourceCulture);
            }
        }
        
        internal static string AllDataWillBeDeletedContinue {
            get {
                return ResourceManager.GetString("AllDataWillBeDeletedContinue", resourceCulture);
            }
        }
        
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        internal static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        internal static string AuthenticationWithBiometricsMessage {
            get {
                return ResourceManager.GetString("AuthenticationWithBiometricsMessage", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string ChooseOther {
            get {
                return ResourceManager.GetString("ChooseOther", resourceCulture);
            }
        }
        
        internal static string ChooseRecent {
            get {
                return ResourceManager.GetString("ChooseRecent", resourceCulture);
            }
        }
        
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string Diary {
            get {
                return ResourceManager.GetString("Diary", resourceCulture);
            }
        }
        
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        internal static string DownloadApp {
            get {
                return ResourceManager.GetString("DownloadApp", resourceCulture);
            }
        }
        
        internal static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string EditIntention {
            get {
                return ResourceManager.GetString("EditIntention", resourceCulture);
            }
        }
        
        internal static string EditSavings {
            get {
                return ResourceManager.GetString("EditSavings", resourceCulture);
            }
        }
        
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        internal static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        internal static string ImportAndExport {
            get {
                return ResourceManager.GetString("ImportAndExport", resourceCulture);
            }
        }
        
        internal static string ImportAndExportText {
            get {
                return ResourceManager.GetString("ImportAndExportText", resourceCulture);
            }
        }
        
        internal static string Intention {
            get {
                return ResourceManager.GetString("Intention", resourceCulture);
            }
        }
        
        internal static string Intentions {
            get {
                return ResourceManager.GetString("Intentions", resourceCulture);
            }
        }
        
        internal static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        internal static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        internal static string Lent {
            get {
                return ResourceManager.GetString("Lent", resourceCulture);
            }
        }
        
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        internal static string MyIntentions {
            get {
                return ResourceManager.GetString("MyIntentions", resourceCulture);
            }
        }
        
        internal static string MyName {
            get {
                return ResourceManager.GetString("MyName", resourceCulture);
            }
        }
        
        internal static string MyPeriodOfLent {
            get {
                return ResourceManager.GetString("MyPeriodOfLent", resourceCulture);
            }
        }
        
        internal static string MyPrayers {
            get {
                return ResourceManager.GetString("MyPrayers", resourceCulture);
            }
        }
        
        internal static string MyReligiousDiary {
            get {
                return ResourceManager.GetString("MyReligiousDiary", resourceCulture);
            }
        }
        
        internal static string MySins {
            get {
                return ResourceManager.GetString("MySins", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string NewIntention {
            get {
                return ResourceManager.GetString("NewIntention", resourceCulture);
            }
        }
        
        internal static string NewMessage {
            get {
                return ResourceManager.GetString("NewMessage", resourceCulture);
            }
        }
        
        internal static string NewPrayer {
            get {
                return ResourceManager.GetString("NewPrayer", resourceCulture);
            }
        }
        
        internal static string NewSin {
            get {
                return ResourceManager.GetString("NewSin", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        internal static string OrderBy {
            get {
                return ResourceManager.GetString("OrderBy", resourceCulture);
            }
        }
        
        internal static string OriginalPrice {
            get {
                return ResourceManager.GetString("OriginalPrice", resourceCulture);
            }
        }
        
        internal static string Payed {
            get {
                return ResourceManager.GetString("Payed", resourceCulture);
            }
        }
        
        internal static string Prayer {
            get {
                return ResourceManager.GetString("Prayer", resourceCulture);
            }
        }
        
        internal static string PrayerFor {
            get {
                return ResourceManager.GetString("PrayerFor", resourceCulture);
            }
        }
        
        internal static string PrayerIntention {
            get {
                return ResourceManager.GetString("PrayerIntention", resourceCulture);
            }
        }
        
        internal static string PrayerRequiredAt {
            get {
                return ResourceManager.GetString("PrayerRequiredAt", resourceCulture);
            }
        }
        
        internal static string Prayers {
            get {
                return ResourceManager.GetString("Prayers", resourceCulture);
            }
        }
        
        internal static string SCREENSHOT_Diary_1_Description {
            get {
                return ResourceManager.GetString("SCREENSHOT_Diary_1_Description", resourceCulture);
            }
        }
        
        internal static string SCREENSHOT_Diary_2_Description {
            get {
                return ResourceManager.GetString("SCREENSHOT_Diary_2_Description", resourceCulture);
            }
        }
        
        internal static string SCREENSHOT_Diary_3_Description {
            get {
                return ResourceManager.GetString("SCREENSHOT_Diary_3_Description", resourceCulture);
            }
        }
        
        internal static string SCREENSHOT_Intention_1_Description {
            get {
                return ResourceManager.GetString("SCREENSHOT_Intention_1_Description", resourceCulture);
            }
        }
        
        internal static string SCREENSHOT_Intention_1_Person {
            get {
                return ResourceManager.GetString("SCREENSHOT_Intention_1_Person", resourceCulture);
            }
        }
        
        internal static string SCREENSHOT_Intention_2_Description {
            get {
                return ResourceManager.GetString("SCREENSHOT_Intention_2_Description", resourceCulture);
            }
        }
        
        internal static string SCREENSHOT_Intention_2_Person {
            get {
                return ResourceManager.GetString("SCREENSHOT_Intention_2_Person", resourceCulture);
            }
        }
        
        internal static string SCREENSHOT_Intention_3_Description {
            get {
                return ResourceManager.GetString("SCREENSHOT_Intention_3_Description", resourceCulture);
            }
        }
        
        internal static string SCREENSHOT_Intention_3_Person {
            get {
                return ResourceManager.GetString("SCREENSHOT_Intention_3_Person", resourceCulture);
            }
        }
        
        internal static string SCREENSHOT_Lent_1_Text {
            get {
                return ResourceManager.GetString("SCREENSHOT_Lent_1_Text", resourceCulture);
            }
        }
        
        internal static string SCREENSHOT_Lent_2_Text {
            get {
                return ResourceManager.GetString("SCREENSHOT_Lent_2_Text", resourceCulture);
            }
        }
        
        internal static string SCREENSHOT_Lent_3_Text {
            get {
                return ResourceManager.GetString("SCREENSHOT_Lent_3_Text", resourceCulture);
            }
        }
        
        internal static string SCREENSHOT_Prayers_1_Description {
            get {
                return ResourceManager.GetString("SCREENSHOT_Prayers_1_Description", resourceCulture);
            }
        }
        
        internal static string SCREENSHOT_Prayers_1_Title {
            get {
                return ResourceManager.GetString("SCREENSHOT_Prayers_1_Title", resourceCulture);
            }
        }
        
        internal static string SCREENSHOT_Prayers_2_Description {
            get {
                return ResourceManager.GetString("SCREENSHOT_Prayers_2_Description", resourceCulture);
            }
        }
        
        internal static string SCREENSHOT_Prayers_2_Title {
            get {
                return ResourceManager.GetString("SCREENSHOT_Prayers_2_Title", resourceCulture);
            }
        }
        
        internal static string SCREENSHOT_Prayers_3_Description {
            get {
                return ResourceManager.GetString("SCREENSHOT_Prayers_3_Description", resourceCulture);
            }
        }
        
        internal static string SCREENSHOT_Prayers_3_Title {
            get {
                return ResourceManager.GetString("SCREENSHOT_Prayers_3_Title", resourceCulture);
            }
        }
        
        internal static string SCREENSHOT_Sins_1_Description {
            get {
                return ResourceManager.GetString("SCREENSHOT_Sins_1_Description", resourceCulture);
            }
        }
        
        internal static string SCREENSHOT_Sins_2_Description {
            get {
                return ResourceManager.GetString("SCREENSHOT_Sins_2_Description", resourceCulture);
            }
        }
        
        internal static string SCREENSHOT_Sins_3_Description {
            get {
                return ResourceManager.GetString("SCREENSHOT_Sins_3_Description", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string SavedAt {
            get {
                return ResourceManager.GetString("SavedAt", resourceCulture);
            }
        }
        
        internal static string SavedMoney {
            get {
                return ResourceManager.GetString("SavedMoney", resourceCulture);
            }
        }
        
        internal static string SavedXThisYear {
            get {
                return ResourceManager.GetString("SavedXThisYear", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        internal static string Sin {
            get {
                return ResourceManager.GetString("Sin", resourceCulture);
            }
        }
        
        internal static string Sins {
            get {
                return ResourceManager.GetString("Sins", resourceCulture);
            }
        }
        
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        internal static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        internal static string TomorrowDayAfter {
            get {
                return ResourceManager.GetString("TomorrowDayAfter", resourceCulture);
            }
        }
        
        internal static string TouchIDEnabled {
            get {
                return ResourceManager.GetString("TouchIDEnabled", resourceCulture);
            }
        }
        
        internal static string UnlockToOpenGodAndMe {
            get {
                return ResourceManager.GetString("UnlockToOpenGodAndMe", resourceCulture);
            }
        }
        
        internal static string WouldYouPrayForX {
            get {
                return ResourceManager.GetString("WouldYouPrayForX", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        internal static string YesterdayDayBefore {
            get {
                return ResourceManager.GetString("YesterdayDayBefore", resourceCulture);
            }
        }
    }
}
