//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GodAndMe.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_es {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_es() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GodAndMe.Resx.AppResources.es", typeof(AppResources_es).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string AddSavings {
            get {
                return ResourceManager.GetString("AddSavings", resourceCulture);
            }
        }
        
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        internal static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        internal static string AuthenticationWithBiometricsMessage {
            get {
                return ResourceManager.GetString("AuthenticationWithBiometricsMessage", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string ChooseOther {
            get {
                return ResourceManager.GetString("ChooseOther", resourceCulture);
            }
        }
        
        internal static string ChooseRecent {
            get {
                return ResourceManager.GetString("ChooseRecent", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string Diary {
            get {
                return ResourceManager.GetString("Diary", resourceCulture);
            }
        }
        
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string EditIntention {
            get {
                return ResourceManager.GetString("EditIntention", resourceCulture);
            }
        }
        
        internal static string EditSavings {
            get {
                return ResourceManager.GetString("EditSavings", resourceCulture);
            }
        }
        
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        internal static string Intention {
            get {
                return ResourceManager.GetString("Intention", resourceCulture);
            }
        }
        
        internal static string Intentions {
            get {
                return ResourceManager.GetString("Intentions", resourceCulture);
            }
        }
        
        internal static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        internal static string Lent {
            get {
                return ResourceManager.GetString("Lent", resourceCulture);
            }
        }
        
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        internal static string MyIntentions {
            get {
                return ResourceManager.GetString("MyIntentions", resourceCulture);
            }
        }
        
        internal static string MyPeriodOfLent {
            get {
                return ResourceManager.GetString("MyPeriodOfLent", resourceCulture);
            }
        }
        
        internal static string MyPrayers {
            get {
                return ResourceManager.GetString("MyPrayers", resourceCulture);
            }
        }
        
        internal static string MyReligiousDiary {
            get {
                return ResourceManager.GetString("MyReligiousDiary", resourceCulture);
            }
        }
        
        internal static string MySins {
            get {
                return ResourceManager.GetString("MySins", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string NewIntention {
            get {
                return ResourceManager.GetString("NewIntention", resourceCulture);
            }
        }
        
        internal static string NewPrayer {
            get {
                return ResourceManager.GetString("NewPrayer", resourceCulture);
            }
        }
        
        internal static string NewSin {
            get {
                return ResourceManager.GetString("NewSin", resourceCulture);
            }
        }
        
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        internal static string OriginalPrice {
            get {
                return ResourceManager.GetString("OriginalPrice", resourceCulture);
            }
        }
        
        internal static string Payed {
            get {
                return ResourceManager.GetString("Payed", resourceCulture);
            }
        }
        
        internal static string Prayer {
            get {
                return ResourceManager.GetString("Prayer", resourceCulture);
            }
        }
        
        internal static string PrayerFor {
            get {
                return ResourceManager.GetString("PrayerFor", resourceCulture);
            }
        }
        
        internal static string PrayerIntention {
            get {
                return ResourceManager.GetString("PrayerIntention", resourceCulture);
            }
        }
        
        internal static string PrayerRequiredAt {
            get {
                return ResourceManager.GetString("PrayerRequiredAt", resourceCulture);
            }
        }
        
        internal static string Prayers {
            get {
                return ResourceManager.GetString("Prayers", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string SavedAt {
            get {
                return ResourceManager.GetString("SavedAt", resourceCulture);
            }
        }
        
        internal static string SavedMoney {
            get {
                return ResourceManager.GetString("SavedMoney", resourceCulture);
            }
        }
        
        internal static string SavedXThisYear {
            get {
                return ResourceManager.GetString("SavedXThisYear", resourceCulture);
            }
        }
        
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        internal static string Sin {
            get {
                return ResourceManager.GetString("Sin", resourceCulture);
            }
        }
        
        internal static string Sins {
            get {
                return ResourceManager.GetString("Sins", resourceCulture);
            }
        }
        
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
